name: ci
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        env:
          CI: true
        run: pnpm install --no-frozen-lockfile

      - name: Linting
        run: pnpm lint

      - name: Testing
        run: pnpm test:ci

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build
